/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-09-01 at 18:33:01 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.billing.model;

/**
 * Model definition for InvoicePayment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class InvoicePayment
        extends com.google.api.client.json.GenericJson
{

    static
    {
        // hack to force ProGuard to consider Transaction used, since otherwise it would be stripped out
        // see https://github.com/google/google-api-java-client/issues/543
        com.google.api.client.util.Data.nullOf( Transaction.class );
    }

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private BankAccount bankAccount;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime dueDate;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String key;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String method;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.Double totalAmount;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.util.List<Transaction> transactions;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    @com.google.api.client.json.JsonString
    private java.lang.Long variableSymbol;

    /**
     * @return value or {@code null} for none
     */
    public BankAccount getBankAccount()
    {
        return bankAccount;
    }

    /**
     * @param bankAccount bankAccount or {@code null} for none
     */
    public InvoicePayment setBankAccount( BankAccount bankAccount )
    {
        this.bankAccount = bankAccount;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public com.google.api.client.util.DateTime getDueDate()
    {
        return dueDate;
    }

    /**
     * @param dueDate dueDate or {@code null} for none
     */
    public InvoicePayment setDueDate( com.google.api.client.util.DateTime dueDate )
    {
        this.dueDate = dueDate;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getKey()
    {
        return key;
    }

    /**
     * @param key key or {@code null} for none
     */
    public InvoicePayment setKey( java.lang.String key )
    {
        this.key = key;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getMethod()
    {
        return method;
    }

    /**
     * @param method method or {@code null} for none
     */
    public InvoicePayment setMethod( java.lang.String method )
    {
        this.method = method;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Double getTotalAmount()
    {
        return totalAmount;
    }

    /**
     * @param totalAmount totalAmount or {@code null} for none
     */
    public InvoicePayment setTotalAmount( java.lang.Double totalAmount )
    {
        this.totalAmount = totalAmount;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.util.List<Transaction> getTransactions()
    {
        return transactions;
    }

    /**
     * @param transactions transactions or {@code null} for none
     */
    public InvoicePayment setTransactions( java.util.List<Transaction> transactions )
    {
        this.transactions = transactions;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Long getVariableSymbol()
    {
        return variableSymbol;
    }

    /**
     * @param variableSymbol variableSymbol or {@code null} for none
     */
    public InvoicePayment setVariableSymbol( java.lang.Long variableSymbol )
    {
        this.variableSymbol = variableSymbol;
        return this;
    }

    @Override
    public InvoicePayment set( String fieldName, Object value )
    {
        return ( InvoicePayment ) super.set( fieldName, value );
    }

    @Override
    public InvoicePayment clone()
    {
        return ( InvoicePayment ) super.clone();
    }

}
